#!/bin/sh /etc/rc.common

START=99
STOP=10

. /lib/functions/ttl-hotspot-changer.sh

start() {
    if [ "$(uci -q get ttl-hotspot-changer.config.enable)" = "1" ]; then
        detect_topology
        apply_ttl_spoof
    else
        echo "[!] ttl-hotspot-changer disabled via UCI config"
    fi
}

stop() {
    clear_rules
}

status() {
    show_rules
}

reload() {
    stop
    start
}

